"""your message

Revision ID: 263bfab8cf13
Revises: b2d250d07e76
Create Date: 2026-01-16 11:22:58.639371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263bfab8cf13'
down_revision = 'b2d250d07e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
